source "https://rubygems.org"

gem "rake"
gem "sinatra"
gem "sinatra-cross_origin"

group :development do
  gem "pry"
  gem "pry-coolline"
  gem "sinatra-reloader"
end

group :test do
  gem 'minitest'
  gem 'minitest-rg'
end
